### ISSUE TITLE
Line 66 throws "callback not a function"

### ISSUE THREAD

**Issue by mjwybrow** [mtgjson/cache#1]
Do you have some unpushed changes to this repo or promise?

Line 66:
`loadPromise.done(ret);`
throws "callback not a function" because ret is a promise object and not a callback function.

Is there a reason that loadPromise is different from the ret promise there at all?

**Comment by lsmoura** [comment]
This was a problem on the promise module. It's fixed now. Just `npm update` and you're good to go.
